### ISSUE TITLE
(COSMETIC) `TX HISTORY` still shows transaction from my wallet after I disconnected it

### ISSUE THREAD

**Issue by michalinacienciala** [threshold-network/token-dashboard#405]
After disconnecting a wallet which has some transactions in `TX HISTORY`, those transactions are still visible.

My steps:
1. Logged to https://dashboard.test.threshold.network/tBTC
2. Connected with an account that has some deposit transactions already made. I can see those transactions in the `TX HISTORY` panel.
![Image](https://user-images.githubusercontent.com/78352137/215292085-e412c6e7-c82d-4c52-8a9b-f4d8581a009b.png)

3. Disconnected the wallet. I can still see the same transactions in the `TX HISTORY` panel (even if I switch between tabs in dApp). I shouldn't.
![Image](https://user-images.githubusercontent.com/78352137/215292071-9f75413e-105f-47f4-bdbb-c1c1ca73e1c8.png)

4. Refreshed the website. Now the transactions are gone.

![Image](https://user-images.githubusercontent.com/78352137/215292139-b565c50f-6bdb-4209-9d86-197c1b1abb74.png)

**Comment by michalinacienciala** [comment]
**Found a bit worse scenario. I was able to see transactions from one account, being logged on another account.**

Let's consider two accounts that I have in my MetaMask:

* `Acc1: 0xC31D206f48EC365bc786563dE7cFb67fDb7e74e4` with following tBTC mints:
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/78352137/215292767-cbc0082a-388f-4cc1-8804-147f604c183c.png">

* `Acc2: 0x58C6A45AcFCc1fD0E5A103Cab2caE00b0B188EC5` with following tBTC mints:
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/78352137/215292812-3d44e2c5-b552-4a31-bd1f-074a9bb5a910.png">

Steps:
1. I open a fresh tab in the browser and go to https://dashboard.test.threshold.network/tBTC
2. I make sure that in my MM plugin I have `Acc2` selected
3. I click `Connect Wallet` -> `MetaMask` -> `View Dashboard`. I can see correct transactions:
![image](https://user-images.githubusercontent.com/78352137/215293194-da072cf3-05e1-4332-8e4e-3341f7a19605.png)
4. Click the account address in the right corner -> Disconnect. Still can see the same transactions.
5. Connect Wallet -> WalletConnect -> scanned QR code in the mobile MetaMask app which has only `Acc1` configured -> Connect. **I can see in dApp that the `Acc1` wallet got connected, but I can see` transactions from `Acc2` in the `TX HISTORY`**:
![image](https://user-images.githubusercontent.com/78352137/215293447-3ebcce6a-6b49-4e03-a137-7f5f10d5565d.png)


**Also found a scenario in which I'm logged on an account, but can't see any of it's transactions in the history:**
1. I open a fresh tab in the browser and go to https://dashboard.test.threshold.network/tBTC
2. I make sure that in my MM plugin I have `Acc1` selected
3. I click `Connect Wallet` -> `MetaMask` -> `View Dashboard`. I can see correct transactions:
![image](https://user-images.githubusercontent.com/78352137/215292935-18a0e8fb-101e-4bbd-a1da-578fb49a129b.png)
4. I open MM plugin, click on `Connected` next to account name and then I choose `Switch to this account` under `Acc2`. I can still see ETH address of `Acc1`, transactions are displayed correctly:
![image](https://user-images.githubusercontent.com/78352137/215293005-c4be72d9-3e5d-4e13-bb97-cfc7739e6575.png).
5. Now I repeat the same, changing to `Acct1`. **Now I don't see any transactions, despite I'm logged with `Acct1` which should have 4 txs**.
![image](https://user-images.githubusercontent.com/78352137/215293035-8b3abb6c-29ef-4a5c-aed0-a08cba719cda.png)

**Comment by michalinacienciala** [comment]
Change priority to MEDIUM (up for debate), because I've got a feeling that this may be also somehow related to the problems that @sashatanase saw on her account, where she had multiple same transactions displayed in her `TX HISTORY`.

**Comment by pdyraga** [comment]
I have observed similar behavior after opening two deposits:

https://goerli.etherscan.io/tx/0x4b952fa926f8826a5c5808e728677477026aeabcd9320b1c0883b82f2dcce9fd
https://goerli.etherscan.io/tx/0x4b952fa926f8826a5c5808e728677477026aeabcd9320b1c0883b82f2dcce9fd

This is how the history is displayed when revealing the second deposit:

![image](https://user-images.githubusercontent.com/4712360/215352482-dfb1ee03-3134-4fc7-a942-716b2f2d7bd7.png)

And this is what is displayed after refreshing the page (and what I'd expect to see):

![image](https://user-images.githubusercontent.com/4712360/215352497-45125447-c191-47e9-a6d6-0c0ab0f0854b.png)

**Comment by pdyraga** [comment]
I have observed similar behavior after opening two deposits:

https://goerli.etherscan.io/tx/0x4b952fa926f8826a5c5808e728677477026aeabcd9320b1c0883b82f2dcce9fd
https://goerli.etherscan.io/tx/0x4b952fa926f8826a5c5808e728677477026aeabcd9320b1c0883b82f2dcce9fd

This is how the history is displayed when revealing the second deposit:

![image](https://user-images.githubusercontent.com/4712360/215352482-dfb1ee03-3134-4fc7-a942-716b2f2d7bd7.png)

And this is what is displayed after refreshing the page (and what I'd expect to see):

![image](https://user-images.githubusercontent.com/4712360/215352497-45125447-c191-47e9-a6d6-0c0ab0f0854b.png)


It looks like the same reveal event is displayed twice sometimes - see the TX hash for the history.

Worth noting, I was not switching accounts and I do not have another account in MetaMask from where I mint tBTC.

**Comment by pdyraga** [comment]
Test

**Comment by pdyraga** [comment]
I have observed similar behavior after opening two deposits:

https://goerli.etherscan.io/tx/0x4b952fa926f8826a5c5808e728677477026aeabcd9320b1c0883b82f2dcce9fd
https://goerli.etherscan.io/tx/0x4b952fa926f8826a5c5808e728677477026aeabcd9320b1c0883b82f2dcce9fd

This is how the history is displayed when revealing the second deposit:

![image](https://user-images.githubusercontent.com/4712360/215352482-dfb1ee03-3134-4fc7-a942-716b2f2d7bd7.png)

And this is what is displayed after refreshing the page (and what I'd expect to see):

![image](https://user-images.githubusercontent.com/4712360/215352497-45125447-c191-47e9-a6d6-0c0ab0f0854b.png)


It looks like the same reveal event is displayed twice sometimes - see the TX hash for the history.

Worth noting, I was not switching accounts and I do not have another account in MetaMask from where I mint tBTC.

**Comment by pdyraga** [comment]
I have observed similar behavior after opening two deposits:

https://goerli.etherscan.io/tx/0x4b952fa926f8826a5c5808e728677477026aeabcd9320b1c0883b82f2dcce9fd
https://goerli.etherscan.io/tx/0x4b952fa926f8826a5c5808e728677477026aeabcd9320b1c0883b82f2dcce9fd

This is how the history is displayed when revealing the second deposit:

![image](https://user-images.githubusercontent.com/4712360/215352482-dfb1ee03-3134-4fc7-a942-716b2f2d7bd7.png)

And this is what is displayed after refreshing the page (and what I'd expect to see):

![image](https://user-images.githubusercontent.com/4712360/215352497-45125447-c191-47e9-a6d6-0c0ab0f0854b.png)


It looks like the same reveal event is displayed twice sometimes - see the TX hash for the history.

Worth noting, I was not switching accounts and I do not have another account in MetaMask from where I mint tBTC.

**Comment by michalinacienciala** [comment]
Looks very similar to Sasha's issue... Unfortunately I can't help with reproduction steps, as I never hit this issue myself...

**Comment by pdyraga** [comment]
It is happening randomly on Chrome for me. There is no clear path for reproducing I am afraid.

**Comment by michalinacienciala** [comment]
I've tested the switching between different accounts now that we've got fixes for those two issues. I never got the wrong operators' transactions in TX HISTORY, but sometimes I got no TX HISTORY data after switching.
In such cases I could see the following error in the Browser's Console:
```listenerMiddleware/error Error: Could not load staking provider's operator info: Error: resolver or addr is not configured for ENS name (argument="name", value="", code=INVALID_ARGUMENT, version=contracts/5.6.2)
    at effects.ts:62:11
    at c (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.throw (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:29:9) {raisedBy: 'effect'}
```
![image](https://user-images.githubusercontent.com/78352137/215497020-f7fa479e-0014-4305-9969-979e5d3033f8.png)

**Comment by michalinacienciala** [comment]
@pdyraga or @sashatanase - I can't verify if problem with the duplicated transactions got resolved by fixes https://github.com/threshold-network/token-dashboard/pull/360 and https://github.com/threshold-network/token-dashboard/pull/409, as it was never occurring on my side. Could you Guys check on your environments?
